#import "./fragments/Beer.gql"
#import "./fragments/Brewery.gql"

query productsQuery($q: String!, $limit: Int, $offset: Int) {
  untappdProducts(q: $q, limit: $limit, offset: $offset) {
    __typename,
    beers {
      count,
      items {
        ...BeerSearchResult
      }
    },
    brewery_id,
    found,
    limit,
    offset,
    message,
    parsed_term,
    search_type,
    search_version,
    term,
    time_taken,
    type_id
  }
}

fragment BeerSearchResult on UntappdSearchResultBeer {
  checkin_count
  beer {
    ...Beer
  }
  brewery {
    ...Brewery
  }
}
